SELECT a.ID, a.USER_LOGIN, a.USER_PASS, a.USER_EMAIL, a.USER_REGISTRO, a.USER_STATUS, a.USER_ROL
FROM PG_USERS a

INSERT INTO PG_USERS VALUES(3, 'nduran', '123456', 'nduran@live.com.mx', '08/09/2015', 'alta', 'usuario')

SELECT USER_LOGIN, USER_PASS 
FROM PG_USERS 
WHERE USER_LOGIN = 'gdeleon' and USER_PASS = '123456'

SELECT USER_LOGIN, USER_PASS FROM PG_USERS WHERE USER_LOGIN = 'fghfdgh' and USER_PASS = 'fdghfgh'

SELECT USER_ROL FROM PG_USERS WHERE USER_LOGIN = 'sdfg'

SELECT * FROM SEG_DOCUMENTOS